export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_BY_CATEGORY = "GET_ALL_PRODUCTS_BY_CATEGORY";
export const GET_ALL_PRODUCTS_BY_NAME = "GET_ALL_PRODUCTS_BY_NAME";
export const GET_ALL_PRODUCTS_BY_PRICE = "GET_ALL_PRODUCTS_BY_PRICE";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_OFFERS = "GET_OFFERS";
export const GET_TOP_RATED_PRODUCTS = "GET_TOP_RATED_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";

export const GET_USER_CART_PRODUCTS = "GET_USER_CART_PRODUCTS";
export const GET_USER_WISHLIST_PRODUCTS = "GET_USER_WISHLIST_PRODUCTS";
export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const GET_USER_ORDERS_BY_DATE = "GET_USER_ORDERS_BY_DATE";
export const GET_USER_DETAILS = "GET_USER_DETAILS";

//  ---------------- ADD ---------------------

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_OFFER = "ADD_OFFER";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_REVIEW_ON_PRODUCT = "ADD_REVIEW_ON_PRODUCT";
// export const ADD_COMMENT_ON_PRODUCT = "ADD_COMMENT_ON_PRODUCT";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const ADD_PRODUCT_TO_WISHLIST = "ADD_PRODUCT_TO_WISHLIST";

export const CREATE_USER = "CREATE_USER";

export const CHECKOUT_ORDER = "CHECKOUT_ORDER";

//  ---------------- EDIT ---------------------

export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_USER = "EDIT_USER";

//  ---------------- DELETE ---------------------

export const DELETE_PRODUCT_FROM_STORE = "DELETE_PRODUCT_FROM_STORE";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const DELETE_PRODUCT_FROM_WISHLIST = "DELETE_PRODUCT_FROM_WISHLIST";
export const DELETE_USER = "DELETE_USER";

// export const CANCEL_ORDER = "CANCEL_ORDER";
